modLoader="kotlinforforge"
loaderVersion="[1.6,)"
license='GNU GPL v3'

[[mods]]
modId="archesmod"
version="${file.jarVersion}"
displayName="ArchesMod"
authors="ArcheCraft"
description='''

'''
[[dependencies.archesmod]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.archesmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"